[project]
name = "instrument-api"
version = "0.1.0"
description = "Instrument recognition API"
requires-python = ">=3.10"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "librosa",
    "numpy",
    "tensorflow",
    "python-multipart",
    "pydantic"
]
